added origin to chat params
eduzz/ui-layout pull request #13
Opened 2024-08-27 18:05 UTC by tecnauta

## What?

## Why?

## How?

## Testing?

## Screenshots (optional)

## Anything Else?

2024-08-27 18:35 UTC, henriquegomes6 approved these changes

2024-08-28 11:52 UTC, miguelaugl approved these changes

2024-08-28 13:10 UTC, henriquegomes6 requested changes

2024-08-28 13:10 UTC, henriquegomes6 commented on README.md
> +  origin: string;
coloca um enum aqui

2024-08-28 18:32 UTC, henriquegomes6 approved these changes

2024-08-28 18:46 UTC, miguelaugl commented on Topbar/HyperflowSupportChat/types.ts
> +enum OriginType {
Ao invés de usar o enum, como é uma lib, coloca valores separados por pipe só pra não precisar exportar e importar o enum

2024-08-28 18:53 UTC, tecnauta commented on Topbar/HyperflowSupportChat/types.ts
> +enum OriginType {
[e9a0f2a](https://github.com/eduzz/ui-layout/pull/13/commits/e9a0f2a10c838e7b622eb81776fefd57e0a86842)

2024-08-28 18:54 UTC, miguelaugl approved these changes

2024-08-28 18:56 UTC, tecnauta commented on README.md
> +  origin: string;
[9d6ed5e](https://github.com/eduzz/ui-layout/pull/13/commits/9d6ed5e2b6524a98710835badd390d6a0d77865a)

2024-08-28 19:22 UTC, henriquegomes6 approved these changes

2024-08-28 19:23 UTC, merged