Hyperflow on topbar
eduzz/ui-layout pull request #7
Opened 2024-07-09 15:40 UTC by tecnauta

## What?
Adicionar o chat do hyperflow no topbar

## Why?
Deixar como um componente único que outros produtos que utilzam a topbar podem implementar. Ainda é necessário chamar no front do produto, e ter o backend que consulta o accounts para pegar o JWT e passar para o Hyperflow

## How?

## Testing?

## Screenshots (optional)

## Anything Else?

2024-07-09 16:32 UTC, caferrari requested changes

2024-07-09 16:32 UTC, caferrari commented on Topbar/HyperflowSupportChat/import.tsx
> +      script.addEventListener('load', handleScript);
esse codigo roda novamenet na linha 28, não precisa dele aqui

2024-07-09 16:34 UTC, danieloprado requested changes

2024-07-09 16:34 UTC, danieloprado commented on Topbar/HyperflowSupportChat/chat.tsx
> +  function getChatTokenID() {
poderia mover esse função para fora do component

2024-07-09 16:34 UTC, danieloprado commented on Topbar/HyperflowSupportChat/chat.tsx
> +  if (!currentUser) return null;
o ideal seria colocar esse logica daqui para baixo em um useEffect.

2024-07-09 16:34 UTC, danieloprado commented on Topbar/HyperflowSupportChat/chat.tsx
> +const SupportChat: React.FC<SupportChatProps> = ({ jwtToHyperflow }) => {
Renomeia esse componente para HyperflowSupportChat

2024-07-12 18:08 UTC, danieloprado approved these changes

2024-08-05 11:20 UTC, merged